name: CI/CD Deploy Java App to Tomcat10 on EC2

# Trigger deployment on push to staging or main, and on PR to staging
on:
  push:
    branches:
      - staging
      - master
  pull_request:
    branches:
      - staging

jobs:
  build:
    name: Build WAR
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2 Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3 Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests

      # 4 Verify WAR file exists
      - name: Verify WAR file
        run: |
          echo "=== Listing target directory ==="
          ls -la target/
          
          echo "=== Checking for WAR files ==="
          if ls target/*.war 1> /dev/null 2>&1; then
            echo "Found WAR files:"
            ls -la target/*.war
            WAR_FILE=$(ls target/*.war | head -1)
            echo "WAR file: $WAR_FILE"
            
            # Verify it's a file, not directory
            if [ -d "$WAR_FILE" ]; then
              echo "ERROR: $WAR_FILE is a directory, not a file!"
              exit 1
            fi
            
            # Copy to a known location with correct name
            cp "$WAR_FILE" ./ROOT.war
            echo "WAR_FILE copied to ./ROOT.war"
          else
            echo "ERROR: No WAR files found in target directory"
            exit 1
          fi

      # 5 Upload WAR artifact for deployment jobs
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: ./ROOT.war

  deploy-staging:
    name: Deploy to Staging
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    
    steps:
      # 1 Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: war-file
          
      # 2 Create SSH key file
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3 Deploy to Staging
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Staging Deployment ==="
            
            # Clean up staging directory
            echo "1. Cleaning up staging directory..."
            sudo rm -rf /var/lib/tomcat10/webapps/staging*
            sudo mkdir -p /var/lib/tomcat10/webapps/staging
            sudo chmod 777 /var/lib/tomcat10/webapps/staging
            
            # Upload WAR file as staging.war (not ROOT.war)
            echo "2. Uploading WAR file to staging..."
            scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
              ./ROOT.war ubuntu@${{ secrets.EC2_HOST }}:/var/lib/tomcat10/webapps/staging.war
            
            # Set permissions
            echo "3. Setting permissions..."
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/staging.war
            sudo chmod 644 /var/lib/tomcat10/webapps/staging.war
            
            # Restart Tomcat
            echo "4. Restarting Tomcat..."
            sudo systemctl restart tomcat10
            
            # Verify deployment
            echo "5. Verifying deployment..."
            sleep 10
            ls -la /var/lib/tomcat10/webapps/
            sudo systemctl status tomcat10 --no-pager
            
            echo "=== Staging Deployment Completed ==="

  deploy-production:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      # 1 Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: war-file
          
      # 2 Create SSH key file
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3 Deploy to Production
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Production Deployment ==="
            
            # Clean up production directory
            echo "1. Cleaning up production directory..."
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT*
            
            # Upload WAR file as ROOT.war
            echo "2. Uploading WAR file to production..."
            scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
              ./ROOT.war ubuntu@${{ secrets.EC2_HOST }}:/var/lib/tomcat10/webapps/ROOT.war
            
            # Set permissions
            echo "3. Setting permissions..."
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 644 /var/lib/tomcat10/webapps/ROOT.war
            
            # Restart Tomcat
            echo "4. Restarting Tomcat..."
            sudo systemctl restart tomcat10
            
            # Verify deployment
            echo "5. Verifying deployment..."
            sleep 10
            ls -la /var/lib/tomcat10/webapps/
            sudo systemctl status tomcat10 --no-pager
            
            echo "=== Production Deployment Completed ==="
